//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YahooFinanceImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        public byte IndicatorId { get; set; }
        public string Name { get; set; }
        public byte PeriodStart { get; set; }
        public byte PeriodEnd { get; set; }
        public string Parameters { get; set; }
    }
}
